replicaCount: 1

image:
  repository: devsecops-assessment-node
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

probes:
  enabled: true
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

namespace: default
releaseName: devsecops-app
